use movies;

-- 1 --
SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'F' 
AND NAME IN (SELECT NAME
			 FROM MOVIEEXEC
			 WHERE NETWORTH > 10000000);

-- 2 --
SELECT NAME
FROM MOVIESTAR
WHERE NAME NOT IN (SELECT NAME
				   FROM MOVIEEXEC);
