-- SHIPS --

use ships;

-- 1 --
SELECT NAME, LAUNCHED
FROM SHIPS
WHERE NAME = CLASS;

-- 2 --
SELECT DISTINCT SHIP
FROM OUTCOMES
WHERE SHIP LIKE 'C%' OR SHIP LIKE 'K%';

-- 3 --
SELECT DISTINCT COUNTRY
FROM CLASSES
JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE RESULT = 'sunk';

-- 4 --
SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE COUNTRY NOT IN (SELECT DISTINCT COUNTRY
					  FROM CLASSES
					  JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
					  JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
					  WHERE RESULT = 'sunk');

-- 5 --
SELECT CLASSES.CLASS
FROM CLASSES
LEFT JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS AND LAUNCHED > 1921
WHERE NAME IS NULL;

-- 6 --
SELECT CLASS, COUNTRY, BORE * 2.54 AS BORE
FROM CLASSES
WHERE NUMGUNS IN (6, 8, 10);

-- 7 --
SELECT DISTINCT c1.COUNTRY
FROM CLASSES c1
JOIN CLASSES c2 ON c1.COUNTRY = c2.COUNTRY AND c1.BORE < c2.BORE;

-- 8 --
SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS >= ALL(SELECT NUMGUNS
					 FROM CLASSES);

-- MOVIES --

use movies;

-- 1 --
SELECT *
FROM MOVIE
WHERE TITLE LIKE '%Star%' AND TITLE LIKE '%Trek%'
ORDER BY YEAR DESC, TITLE ASC;

-- 2 --
SELECT DISTINCT MOVIETITLE
FROM STARSIN
JOIN MOVIESTAR ON NAME = STARNAME
WHERE YEAR(BIRTHDATE) >= 1970 AND YEAR(BIRTHDATE) < 1980;

-- PC --

use pc;

-- 1 --
SELECT PC.*
FROM PC
JOIN PRODUCT pr1 ON pr1.MODEL = PC.MODEL 
WHERE PRICE < ALL(SELECT PRICE
				  FROM LAPTOP
				  JOIN PRODUCT pr2 ON pr2.MODEL = LAPTOP.MODEL
				  WHERE pr1.MAKER = pr2.MAKER);

-- 2 --
SELECT PC.*
FROM PC
JOIN PRODUCT pr1 ON pr1.MODEL = PC.MODEL 
WHERE PRICE < ALL(SELECT PRICE
				  FROM LAPTOP
				  JOIN PRODUCT pr2 ON pr2.MODEL = LAPTOP.MODEL
				  WHERE pr1.MAKER = pr2.MAKER)
AND PRICE < ALL(SELECT PRICE
				  FROM PRINTER
				  JOIN PRODUCT pr2 ON pr2.MODEL = PRINTER.MODEL
				  WHERE pr1.MAKER = pr2.MAKER);
