use pc;

-- 1 --
SELECT DISTINCT PRODUCT.MODEL, PRICE
FROM PRODUCT
LEFT JOIN PC ON PRODUCT.MODEL = PC.MODEL
WHERE product.TYPE = 'PC';

-- 2 --
SELECT DISTINCT MAKER, MODEL, TYPE
FROM PRODUCT
WHERE MODEL NOT IN (
					(SELECT MODEL FROM PC)
					UNION
					(SELECT MODEL FROM LAPTOP)
					UNION
					(SELECT MODEL FROM PRINTER)
					);
