use movies;

-- 1 --
SELECT STARNAME, COUNT(DISTINCT STUDIONAME) AS COUNT_STUDIOS
FROM STARSIN
JOIN MOVIE ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
GROUP BY STARNAME;

-- 2 --
SELECT NAME, COUNT(DISTINCT STUDIONAME) AS COUNT_STUDIOS
FROM MOVIESTAR
LEFT JOIN STARSIN ON STARNAME = NAME
LEFT JOIN MOVIE ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
GROUP BY NAME;

-- 3 --
SELECT STARNAME
FROM STARSIN
WHERE MOVIEYEAR > 1990
GROUP BY STARNAME
HAVING COUNT(*) >= 3;
