use ships;

-- 1 --
SELECT COUNT(*) AS COUNT_CLASS
FROM CLASSES;

-- 2 --
SELECT AVG(NUMGUNS) AS AVG_GUNS
FROM CLASSES
JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS;

-- 3 --
SELECT CLASSES.CLASS, MIN(LAUNCHED) AS FIRST_YEAR, MAX(LAUNCHED) AS LAST_YEAR
FROM CLASSES
LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY CLASSES.CLASS;

-- 4 --
SELECT CLASSES.CLASS, COUNT(BATTLE) AS SUNK_COUNT
FROM CLASSES
LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
LEFT JOIN OUTCOMES ON SHIP = NAME AND RESULT = 'sunk'
GROUP BY CLASSES.CLASS;

-- 5 --
SELECT CLASS, COUNT(RESULT)
FROM SHIPS
LEFT JOIN OUTCOMES ON SHIP = NAME AND RESULT = 'sunk'
WHERE CLASS IN (SELECT CLASS
				FROM SHIPS
				GROUP BY CLASS
				HAVING COUNT(*) >= 4)
GROUP BY CLASS;

-- 6 --
SELECT COUNTRY, AVG(DISPLACEMENT) AS AVG_DISPLACEMENT
FROM CLASSES
GROUP BY COUNTRY;
