use ships;

-- 1 --
SELECT COUNT(*) AS COUNT_CLASS
FROM CLASSES;

-- 2 --
SELECT AVG(NUMGUNS) AS AVG_GUNS
FROM CLASSES
JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS;

-- 3 --
SELECT CLASS, MIN(LAUNCHED) AS FIRST_YEAR, MAX(LAUNCHED) AS LAST_YEAR
FROM SHIPS
GROUP BY CLASS;

-- 4 --
SELECT CLASS, COUNT(*) AS COUNT_SUNK
FROM SHIPS
JOIN OUTCOMES ON SHIP = NAME
WHERE RESULT = 'sunk'
GROUP BY CLASS;

-- 5 --
SELECT CLASS, COUNT(*)
FROM SHIPS
JOIN OUTCOMES ON SHIP = NAME
WHERE RESULT = 'sunk'
AND CLASS IN (SELECT CLASS
			  FROM SHIPS
			  GROUP BY CLASS
			  HAVING COUNT(*) > 4)
GROUP BY CLASS;

-- 6 --
SELECT COUNTRY, AVG(DISPLACEMENT) AS AVG_DISPLACEMENT
FROM CLASSES
GROUP BY COUNTRY;
