-- SHIPS --

use ships;

-- 1 --
SELECT BATTLE, COUNT(*) AS COUNT_SUNK
FROM OUTCOMES
JOIN SHIPS ON NAME = SHIP
JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
WHERE COUNTRY = 'USA' AND RESULT = 'sunk'
GROUP BY BATTLE;

-- 2 --
SELECT DISTINCT BATTLE
FROM OUTCOMES
JOIN SHIPS ON NAME = SHIP
JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY COUNTRY, BATTLE
HAVING COUNT(*) >= 3;

-- 3 --
SELECT DISTINCT CLASS
FROM SHIPS
WHERE CLASS NOT IN (SELECT DISTINCT CLASS
					FROM SHIPS
					WHERE LAUNCHED > 1921);

-- 4 --
SELECT DISTINCT NAME, COUNT(BATTLE) AS COUNT
FROM SHIPS
LEFT JOIN OUTCOMES ON NAME = SHIP AND RESULT = 'damaged'
GROUP BY NAME;

-- 5 --
SELECT COUNTRY, COUNT(SHIPS.NAME) AS COUNT_ALL, COUNT(OUTCOMES.SHIP) AS COUNT_SUNK
FROM CLASSES
LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
LEFT JOIN OUTCOMES ON NAME = SHIP AND RESULT = 'sunk'
GROUP BY COUNTRY;

-- 6 --
SELECT COUNTRY, COUNT(DISTINCT d.SHIP) AS COUNT_DAMAGED, COUNT(DISTINCT s.SHIP) AS COUNT_SUNK
FROM CLASSES
LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
LEFT JOIN OUTCOMES d ON d.SHIP = NAME AND d.RESULT = 'damaged'
LEFT JOIN OUTCOMES S ON s.SHIP = NAME AND s.RESULT = 'sunk'
GROUP BY COUNTRY;

-- 7 --
SELECT CLASS, SUM(CASE result WHEN 'ok' THEN 1 ELSE 0 END) AS COUNT_OK
FROM SHIPS
LEFT JOIN OUTCOMES ON SHIP = NAME
GROUP BY CLASS
HAVING COUNT(DISTINCT NAME) >= 3;

-- 8 --
SELECT NAME, LAUNCHED
FROM SHIPS
WHERE CLASS NOT LIKE '%i%' AND CLASS NOT LIKE '%k%'
ORDER BY LAUNCHED DESC;

-- 9 --
SELECT DISTINCT BATTLE
FROM OUTCOMES
JOIN SHIPS ON NAME = SHIP
JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
WHERE COUNTRY = 'Japan' AND RESULT = 'damaged';

-- 10 --
SELECT DISTINCT BATTLE, s1.CLASS
FROM OUTCOMES
JOIN SHIPS ON NAME = SHIP
JOIN CLASSES s1 ON SHIPS.CLASS = s1.CLASS
WHERE LAUNCHED = (SELECT LAUNCHED + 1
				  FROM SHIPS
				  WHERE NAME = 'Rodney')
AND s1.NUMGUNS > (SELECT AVG(NUMGUNS)
				  FROM CLASSES
				  WHERE COUNTRY = s1.COUNTRY
				  GROUP BY COUNTRY);

-- 11 --
SELECT CLASSES.CLASS 
FROM SHIPS
JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
WHERE COUNTRY = 'USA'
GROUP BY CLASSES.CLASS
HAVING MAX(LAUNCHED) - MIN(LAUNCHED) > 10;

-- 12 --
SELECT DISTINCT BATTLE, COUNT(*) / COUNT(DISTINCT COUNTRY) AS AVG_SHIPS
FROM OUTCOMES
JOIN SHIPS ON SHIP = NAME
JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY BATTLE;

-- 13 --
SELECT 
	DISTINCT COUNTRY,
	COUNT(DISTINCT s1.NAME) AS COUNT_ALL,
	COUNT(DISTINCT o1.BATTLE) AS COUNT_BATTLES,
	COUNT(DISTINCT o2.BATTLE) AS COUNT_SUNK
FROM CLASSES
LEFT JOIN SHIPS s1 ON s1.CLASS = CLASSES.CLASS
LEFT JOIN OUTCOMES o1 ON s1.NAME = o1.SHIP
LEFT JOIN OUTCOMES o2 ON s1.NAME = o2.SHIP AND o2.RESULT = 'sunk'
GROUP BY COUNTRY;
