use movies;

-- 1 --
(
	SELECT 'before 60s' AS PERIOD, COUNT(*) AS COUNT
	FROM MOVIESTAR 
	WHERE YEAR(BIRTHDATE) < 1960
)
UNION
(
	SELECT '60s' AS PERIOD, COUNT(*) AS NUMBER_OF_BIRTHS
	FROM MOVIESTAR
	WHERE YEAR(BIRTHDATE) >= 1960 AND YEAR(BIRTHDATE) < 1970
)
UNION
(
	SELECT '70s' AS PERIOD, COUNT(*) AS NUMBER_OF_BIRTHS
	FROM MOVIESTAR 
	WHERE YEAR(BIRTHDATE) >= 1970 AND YEAR(BIRTHDATE) < 1980
)
UNION
(
	SELECT 'after 70s' AS PERIOD, COUNT(*) AS NUMBER_OF_BIRTHS
	FROM MOVIESTAR
	WHERE YEAR(BIRTHDATE) >= 1980
);
