use ships;

-- 1 --
SELECT DISTINCT BATTLE
FROM OUTCOMES
JOIN SHIPS ON NAME = SHIP
JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
WHERE NUMGUNS < 9
GROUP BY BATTLE
HAVING COUNT(*) >= 3 
AND SUM(CASE RESULT
		  WHEN 'ok' THEN 1
		  ELSE 0
		END) >= 2;
