use ships;

-- 1 --
BEGIN TRANSACTION;

INSERT INTO CLASSES
VALUES ('Nelson', 'bb', 'Gr.Britain', 9, 16, 34000);

INSERT INTO SHIPS
VALUES ('Nelson', 'Nelson', 1927),
	   ('Rodney', 'Nelson', 1927);

ROLLBACK TRANSACTION;

-- 2 --
BEGIN TRANSACTION;

DELETE
FROM SHIPS
WHERE NAME IN (SELECT SHIP
			   FROM OUTCOMES
			   WHERE RESULT = 'sunk');

ROLLBACK TRANSACTION;

-- 3 --
BEGIN TRANSACTION;

UPDATE CLASSES
SET BORE = BORE * 2.54, DISPLACEMENT = DISPLACEMENT / 1.1;

ROLLBACK TRANSACTION;

-- 4 --
BEGIN TRANSACTION;

DELETE CLASSES
WHERE CLASS NOT IN (SELECT CLASS
					FROM SHIPS
					GROUP BY CLASS
					HAVING COUNT(*) >= 3);

ROLLBACK TRANSACTION;

-- 5 --
BEGIN TRANSACTION;

UPDATE CLASSES
SET DISPLACEMENT = (SELECT DISPLACEMENT
					FROM CLASSES
					WHERE CLASS = 'Bismark'),
	BORE = (SELECT BORE
			FROM CLASSES
			WHERE CLASS = 'Bismark')
WHERE CLASS = 'Iowa';

ROLLBACK TRANSACTION;
