use pc;

-- 1 --
BEGIN TRANSACTION;

INSERT INTO PRODUCT(MODEL, MAKER, TYPE)
VALUES ('1100', 'C', 'PC');
INSERT INTO PC(CODE, MODEL, SPEED, RAM, HD, CD, PRICE)
VALUES(12, '1100', 2400, 2048, 500, '52x', 299);

ROLLBACK TRANSACTION;

-- 2 --
BEGIN TRANSACTION;

DELETE
FROM PC
WHERE MODEL = '1100';
DELETE
FROM PRODUCT
WHERE MODEL = '1100';

ROLLBACK TRANSACTION;

-- 3 --
BEGIN TRANSACTION;

INSERT INTO LAPTOP(CODE, MODEL, SPEED, RAM, HD, PRICE, SCREEN)
SELECT CODE + 100, MODEL, SPEED, RAM, HD, PRICE + 500, 15
FROM PC;

ROLLBACK TRANSACTION;

-- 4 --
BEGIN TRANSACTION;

DELETE
FROM LAPTOP
WHERE MODEL IN (SELECT MODEL
				FROM PRODUCT
				WHERE TYPE = 'Laptop'
				AND MAKER NOT IN (SELECT MAKER
								  FROM PRODUCT
								  WHERE TYPE = 'Printer'));

ROLLBACK TRANSACTION;

-- 5 --
BEGIN TRANSACTION;

UPDATE PRODUCT
SET MAKER = 'A'
WHERE MAKER = 'B';

ROLLBACK TRANSACTION;

-- 6 --
BEGIN TRANSACTION;

UPDATE PC
SET PRICE = PRICE / 2, HD = HD + 20;

ROLLBACK TRANSACTION;

-- 7 --
BEGIN TRANSACTION;

UPDATE LAPTOP
SET SCREEN = SCREEN + 1
WHERE MODEL IN (SELECT MODEL
				FROM PRODUCT
				WHERE MAKER = 'B');

ROLLBACK TRANSACTION;
