use movies;

-- 1 --
ALTER TABLE MOVIE
ADD CONSTRAINT unique_len
	UNIQUE(LENGTH);

ALTER TABLE MOVIE
ADD CONSTRAINT unique_studio_len
	UNIQUE(STUDIONAME, LENGTH);

-- 2 --
ALTER TABLE MOVIE
DROP CONSTRAINT unique_len, unique_studio_len;

-- 3 --
CREATE DATABASE studentdb;
GO
use studentdb;
GO

CREATE TABLE Student(
	FN INTEGER PRIMARY KEY 
		CHECK (FN >= 0 AND FN <= 99999),
	NAME VARCHAR(100) NOT NULL,
	EGN CHAR(10) UNIQUE NOT NULL,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	BIRTHDATE DATE NOT NULL,
	ENROLLED DATE NOT NULL,
	CONSTRAINT enroll_adult 
		CHECK (DATEDIFF(YEAR, BIRTHDATE, ENROLLED) >= 18)
);
CREATE TABLE Course(
	ID INTEGER IDENTITY PRIMARY KEY,
	NAME VARCHAR(200)
);
CREATE TABLE Enrollment(
	COURSE_ID INTEGER REFERENCES COURSE(ID) ON DELETE CASCADE,
	STUDENT_FN INTEGER REFERENCES STUDENT(FN),
	PRIMARY KEY(COURSE_ID, STUDENT_FN)
);

ALTER TABLE STUDENT
ADD CONSTRAINT email_format 
	CHECK (EMAIL LIKE '%_@%_.%_');

use pc;
GO 
DROP DATABASE studentdb;
GO
