use pc;
GO

-- 1 --
CREATE VIEW pc_1
AS
	(SELECT CODE, MODEL, PRICE
	 FROM PRINTER)
	 UNION ALL
	(SELECT CODE, MODEL, PRICE
	 FROM LAPTOP)
	 UNION ALL
	(SELECT CODE, MODEL, PRICE
	 FROM PC);

GO

-- 2 --
ALTER VIEW pc_1(CODE, MODEL, PRICE, TYPE)
AS
	(SELECT CODE, MODEL, PRICE, 'Printer'
	 FROM PRINTER)
	 UNION ALL
	(SELECT CODE, MODEL, PRICE, 'Laptop'
	 FROM LAPTOP)
	 UNION ALL
	(SELECT CODE, MODEL, PRICE, 'PC'
	 FROM PC);

GO

-- 3 --
ALTER VIEW pc_1(CODE, MODEL, PRICE, TYPE, SPEED)
AS
	(SELECT CODE, MODEL, PRICE, 'Printer', NULL
	 FROM PRINTER)
	 UNION ALL
	(SELECT CODE, MODEL, PRICE, 'Laptop', SPEED
	 FROM LAPTOP)
	 UNION ALL
	(SELECT CODE, MODEL, PRICE, 'PC', SPEED
	 FROM PC);
