use movies;
GO

-- 1 --
CREATE TRIGGER bruce
ON MOVIE
AFTER INSERT
AS
	INSERT INTO STARSIN
	SELECT TITLE, YEAR, 'Bruce Willis'
	FROM INSERTED
	WHERE TITLE LIKE '%save%' OR TITLE LIKE '%world%';
GO

DROP TRIGGER bruce;
GO

-- 2 --
CREATE TRIGGER networth500
ON MOVIEEXEC
AFTER INSERT, UPDATE, DELETE
AS
	IF ((SELECT AVG(NETWORTH) FROM MOVIEEXEC) < 500000)
	BEGIN
		ROLLBACK TRANSACTION;
	END;
GO

DROP TRIGGER networth500;
GO 

-- 3 --
CREATE TRIGGER setnull
ON MOVIEEXEC
INSTEAD OF DELETE
AS
BEGIN
	UPDATE MOVIE
	SET PRODUCERC# = NULL
	WHERE PRODUCERC# = (SELECT CERT# FROM DELETED);
	DELETE
	FROM MOVIEEXEC
	WHERE CERT# IN (SELECT CERT# FROM DELETED);
END;
GO

DROP TRIGGER setnull;
GO

-- 4 --
CREATE TRIGGER fillstars
ON STARSIN
INSTEAD OF INSERT
AS
BEGIN
	INSERT INTO MOVIESTAR(NAME)
	SELECT DISTINCT STARNAME
	FROM INSERTED
	WHERE STARNAME NOT IN (SELECT NAME
						   FROM MOVIESTAR);

	INSERT INTO MOVIE(TITLE, YEAR)
	SELECT DISTINCT MOVIETITLE, MOVIEYEAR
	FROM INSERTED
	WHERE NOT EXISTS(SELECT *
					 FROM MOVIE
					 WHERE TITLE = MOVIETITLE
					 AND YEAR = MOVIEYEAR);

	INSERT INTO STARSIN
	SELECT MOVIETITLE, MOVIEYEAR, STARNAME
	FROM INSERTED;
END;
