use ships;

GO

-- 1 --
(
	SELECT SHIP AS RESULT
	FROM OUTCOMES
	WHERE BATTLE LIKE '%M%' OR BATTLE LIKE '%R%'
)
UNION
(
	SELECT COUNTRY AS RESULT
	FROM CLASSES
	WHERE DISPLACEMENT > 40000 AND DISPLACEMENT < 50000
)
ORDER BY RESULT DESC;

-- 2 --
INSERT INTO SHIPS(NAME, CLASS, LAUNCHED)
SELECT CLASSES.CLASS, CLASSES.CLASS, MIN(LAUNCHED)
FROM CLASSES
LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
WHERE CLASSES.CLASS NOT IN (SELECT NAME
							FROM SHIPS)
GROUP BY CLASSES.CLASS;

-- 3 --
CREATE VIEW	japanese_ships
AS
SELECT CLASSES.CLASS,
	   NUMGUNS,
	   MIN(LAUNCHED) AS MIN_LAUNCHED,
	   SUM(CASE RESULT WHEN 'damaged' THEN 1 ELSE 0 END) AS COUNT_DAMAGED
FROM CLASSES 
LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
LEFT JOIN OUTCOMES ON SHIP = NAME
WHERE COUNTRY = 'Japan'
GROUP BY CLASSES.CLASS, NUMGUNS;

GO

-- 4 --
CREATE TRIGGER delete_battles
ON BATTLES
INSTEAD OF DELETE
AS
BEGIN
	IF ('Default' NOT IN (SELECT NAME
						  FROM BATTLES))
	BEGIN
		INSERT INTO BATTLES(NAME, DATE)
		VALUES ('Default', '2023-01-01');
	END;

	UPDATE OUTCOMES
	SET BATTLE = 'Default'
	WHERE BATTLE IN (SELECT NAME
					 FROM DELETED);

	DELETE FROM BATTLES
	WHERE NAME IN (SELECT NAME
				   FROM DELETED);
END;
