use pc;

-- 1 --
SELECT MAKER, SPEED
FROM LAPTOP
JOIN PRODUCT ON PRODUCT.MODEL = LAPTOP.MODEL
WHERE HD >= 9;

-- 2 --
(
	SELECT LAPTOP.MODEL, PRICE
	FROM LAPTOP
	JOIN PRODUCT ON LAPTOP.MODEL = PRODUCT.MODEL
	WHERE MAKER = 'B'
)
UNION
(
	SELECT PC.MODEL, PRICE
	FROM PC
	JOIN PRODUCT ON PC.MODEL = PRODUCT.MODEL
	WHERE MAKER = 'B'
)
UNION
(
	SELECT PRINTER.MODEL, PRICE
	FROM PRINTER
	JOIN PRODUCT ON PRINTER.MODEL = PRODUCT.MODEL
	WHERE MAKER = 'B'
)
ORDER BY PRICE;

-- 3 --
SELECT DISTINCT p1.HD
FROM PC p1
JOIN PC p2 ON p1.HD = p2.HD AND NOT (p1.CODE = p2.CODE);

-- 4 --
SELECT DISTINCT p1.MODEL, p2.MODEL
FROM PC p1
JOIN PC p2 ON p1.SPEED = p2.SPEED AND p1.RAM = p2.RAM
WHERE p1.MODEL < p2.model;

-- 5 --
SELECT DISTINCT p1.MAKER
FROM PC pc1
JOIN PRODUCT p1 ON pc1.MODEL = p1.MODEL
JOIN PRODUCT p2 ON p1.MAKER = p2.MAKER
JOIN PC pc2 ON pc2.MODEL = p2.MODEL
WHERE 
	NOT (pc1.CODE = pc2.CODE)
	AND pc1.SPEED >= 500
	AND pc2.SPEED >= 500;
