USE movies;

-- 1 --
SELECT STARNAME
FROM STARSIN
JOIN MOVIESTAR ON STARNAME = NAME
WHERE GENDER = 'F' AND MOVIETITLE = 'Terms of Endearment';

-- 2 --
SELECT STARNAME
FROM STARSIN
JOIN MOVIE ON MOVIETITLE = TITLE AND MOVIEYEAR = YEAR
WHERE STUDIONAME = 'MGM' AND YEAR = 1995;
