use ships;

-- 1 --
SELECT NAME
FROM SHIPS
JOIN CLASSES ON SHIPS.NAME = CLASSES.CLASS
WHERE DISPLACEMENT > 35000;

-- 2 --
SELECT NAME, DISPLACEMENT, NUMGUNS
FROM OUTCOMES
JOIN SHIPS ON SHIP = NAME
JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE BATTLE = 'Guadalcanal';

-- 3 --
SELECT DISTINCT c1.COUNTRY
FROM CLASSES c1
JOIN CLASSES c2 ON c1.COUNTRY = c2.COUNTRY
WHERE c1.TYPE = 'bb' AND c2.TYPE = 'bc';

-- 4 --
SELECT DISTINCT o1.SHIP
FROM OUTCOMES o1 
JOIN BATTLES b1 ON o1.BATTLE = b1.NAME
JOIN OUTCOMES o2 ON o1.SHIP = o2.SHIP
JOIN BATTLES b2 ON o2.BATTLE = b2.NAME
WHERE o1.RESULT = 'damaged' AND b1.DATE < b2.DATE;
