use movies;

-- 1 --
SELECT DISTINCT TITLE, YEAR, STUDIONAME, ADDRESS
FROM MOVIE
LEFT JOIN STUDIO ON NAME = STUDIONAME
WHERE LENGTH > 120;

-- 2 --
SELECT DISTINCT STARNAME, STUDIONAME
FROM STARSIN
JOIN MOVIE ON STARSIN.MOVIETITLE = MOVIE.TITLE AND STARSIN.MOVIEYEAR = MOVIE.YEAR
ORDER BY STUDIONAME;

-- 3 --
SELECT DISTINCT NAME
FROM MOVIE
JOIN MOVIEEXEC ON PRODUCERC# = CERT#
JOIN STARSIN ON (STARSIN.MOVIETITLE = MOVIE.TITLE 
				 AND STARSIN.MOVIEYEAR = MOVIE.YEAR 
				 AND STARNAME = 'Harrison Ford');

-- 4 --
SELECT DISTINCT STARNAME
FROM STARSIN
JOIN MOVIE ON (STARSIN.MOVIETITLE = MOVIE.TITLE
			   AND STARSIN.MOVIEYEAR = MOVIE.YEAR 
			   AND STUDIONAME = 'MGM')
JOIN MOVIESTAR ON MOVIESTAR.NAME = STARNAME AND GENDER = 'F';

-- 5 --
SELECT TITLE, NAME
FROM MOVIE
JOIN MOVIEEXEC ON PRODUCERC# = CERT#
WHERE NAME IN (SELECT DISTINCT NAME
			   FROM MOVIEEXEC
			   JOIN MOVIE ON CERT# = PRODUCERC# AND TITLE = 'Star Wars');

-- 6 --
SELECT NAME
FROM MOVIESTAR
LEFT JOIN STARSIN ON STARNAME = NAME
WHERE MOVIETITLE IS NULL;
