use pc;

-- 1 --
SELECT AVG(SPEED) AS AVG_SPEED
FROM PC;

-- 2 --
SELECT MAKER, AVG(SCREEN) AS AVG_SCREEN
FROM LAPTOP
JOIN PRODUCT ON PRODUCT.MODEL = LAPTOP.MODEL
GROUP BY MAKER;

-- 3 --
SELECT AVG(SPEED) AS AVG_SPEED
FROM LAPTOP
WHERE PRICE > 1000;

-- 4 --
SELECT AVG(PRICE) AS AVG_PRICE
FROM PC
JOIN PRODUCT ON PRODUCT.MODEL = PC.MODEL
WHERE MAKER = 'A';

-- 5 --
SELECT AVG(PRICE) AS AVG_PRICE
FROM (
	(
		SELECT PRICE
		FROM PC
		JOIN PRODUCT ON PC.MODEL = PRODUCT.MODEL
		WHERE MAKER = 'B'
	)
	 UNION ALL
	(
		SELECT PRICE
		FROM LAPTOP
		JOIN PRODUCT ON LAPTOP.MODEL = PRODUCT.MODEL
		WHERE MAKER = 'B'
	)
) unionB;

-- 6 --
SELECT AVG(PRICE) AS AVG_PRICE
FROM PC
GROUP BY SPEED;

-- 7 --
SELECT MAKER
FROM PRODUCT
WHERE TYPE = 'PC'
GROUP BY MAKER
HAVING COUNT(*) >= 3;

-- 8 --
SELECT DISTINCT MAKER
FROM PRODUCT
JOIN PC ON PC.MODEL = PRODUCT.MODEL
WHERE PRICE = (SELECT MAX(PRICE)
			   FROM PC);

-- 9 --
SELECT SPEED, AVG(PRICE) AS AVG_PRICE
FROM PC
WHERE SPEED > 800
GROUP BY SPEED;

-- 10 --
SELECT AVG(HD) AS AVG_HD
FROM PC
JOIN PRODUCT ON PC.MODEL = PRODUCT.MODEL
WHERE MAKER IN (SELECT MAKER
				FROM PRODUCT
				WHERE TYPE = 'Printer');

-- 11 --
SELECT SCREEN, (MAX(PRICE) - MIN(PRICE)) AS PRICE_DIFFERENCE
FROM LAPTOP
GROUP BY SCREEN;

-- 12 --
SELECT MODEL
FROM PC
GROUP BY MODEL
ORDER BY MAX(PRICE);
