use ships;

-- 1 --
SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS >= ALL(SELECT NUMGUNS
					 FROM CLASSES);

-- 2 --
SELECT NAME
FROM SHIPS
WHERE CLASS IN (SELECT CLASS
				FROM CLASSES
				WHERE BORE = 16);

-- 3 --
SELECT DISTINCT BATTLE
FROM OUTCOMES
WHERE SHIP IN (SELECT NAME
			   FROM SHIPS
			   WHERE CLASS = 'Kongo');

-- 4 --
SELECT NAME
FROM SHIPS
JOIN CLASSES cl1 ON SHIPS.CLASS = cl1.CLASS
WHERE cl1.NUMGUNS >= ALL(SELECT NUMGUNS
						 FROM CLASSES
						 WHERE BORE = cl1.BORE);
