use pc;

-- LIST CONDITIONS --
SELECT *
FROM PRINTER
WHERE PRICE >= ALL(SELECT PRICE 
				   FROM PRINTER);
-- TOP --
SELECT TOP 1 *
FROM PRINTER
ORDER BY PRICE DESC;

SELECT TOP 1 *
FROM PRINTER
WHERE PRICE >= ALL(SELECT PRICE
				   FROM PRINTER);

use ships;

SELECT DISTINCT CLASS
FROM SHIPS
WHERE NAME IN (SELECT SHIP
			   FROM OUTCOMES
			   WHERE RESULT = 'sunk');

SELECT DISTINCT CLASS
FROM CLASSES
WHERE CLASS NOT IN (SELECT DISTINCT CLASS
					FROM SHIPS
					WHERE NAME IN (SELECT SHIP
								   FROM OUTCOMES
								   WHERE RESULT = 'sunk'));

use movies;

-- CORRELATIVE SUBQUERIES --
SELECT DISTINCT TITLE
FROM MOVIE m
WHERE YEAR < ANY (SELECT YEAR
				  FROM MOVIE
				  WHERE TITLE = m.TITLE);

-- EXISTS --
SELECT NAME
FROM MOVIESTAR
WHERE EXISTS (SELECT 1
			  FROM STARSIN
			  WHERE MOVIESTAR.NAME = STARNAME
					AND MOVIEYEAR >= YEAR(MOVIESTAR.BIRTHDATE) + 40);
